package com.coderscampus.week9;

import java.util.Objects;

public class Person {

	private Integer ssn;
	private String firstName;
	private String lastName;
	
	// this was generated by selecting generate constructor and changing the variable names to their corresponding values
	public Person(int ssn, String firstName, String lastName) {
		this.ssn = ssn;
		this.firstName = firstName;
		this.lastName = lastName;
	}
	
	
	// Source -> Generate HashCode and Equals
	// this is to setup which field will be used to set the unique identifier
	
	@Override
	public int hashCode() {
		return Objects.hash(ssn);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Person other = (Person) obj;
		return Objects.equals(ssn, other.ssn);
	}
	
	// it is recommended to ALWAYS override equals and hashCode
	

	public Integer getSsn() {
		return ssn;
	}
	public String getFirstName() {
		return firstName;
	}
	public String getLastName() {
		return lastName;
	}
	
	
	public void setSsn(Integer ssn) {
		this.ssn = ssn;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	
	@Override
	public String toString() {
		return "Person [ssn=" + ssn + ", firstName=" + firstName + ", lastName=" + lastName + "]";
	}
	
	
}
